name: EC2-Deployment

on:
  workflow_dispatch:
    inputs:
      ami_version:
        required: true
        description: 'AMI Version'

permissions:
  contents: read
  id-token: write

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} 

jobs:
  deploy-ec2:
    name: EC2 Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform 
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }} 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "custom_ami_version=${{ github.event.inputs.ami_version }}"

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        id: apply
        run: terraform apply -var "custom_ami_version=${{ github.event.inputs.ami_version }}" -auto-approve

      - name: Public IP Output
        run: |
          echo "Public IP: $(terraform output ec2_public_ip | tr -d '""')"